import { UserPlus, Target, Brain, TrendingUp } from 'lucide-react'
import Link from 'next/link'

const HowItWorks = () => {
  const steps = [
    {
      icon: UserPlus,
      title: 'Sign Up',
      description: 'Create your account in seconds with our streamlined registration process',
      step: '01',
    },
    {
      icon: Target,
      title: 'Set Goals',
      description: 'Tell us your fitness objectives, preferences, and current fitness level',
      step: '02',
    },
    {
      icon: Brain,
      title: 'Get AI Plans',
      description: 'Receive personalized workout & meal plans generated by our advanced AI',
      step: '03',
    },
    {
      icon: TrendingUp,
      title: 'Track Progress',
      description: 'Monitor your transformation journey with detailed analytics and insights',
      step: '04',
    },
  ]

  return (
    <section id="how-it-works" className="py-20 bg-maxfit-black">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="text-center mb-16">
          <h2 className="text-4xl lg:text-5xl font-bold text-white mb-6">
            How <span className="text-maxfit-neon-green text-glow">MAXFITAI</span> Works
          </h2>
          <p className="text-xl text-gray-300 max-w-3xl mx-auto">
            Get started with AI-powered fitness in just four simple steps
          </p>
        </div>

        <div className="relative">
          {/* Connection Line */}
          <div className="hidden lg:block absolute top-1/2 left-0 right-0 h-0.5 bg-gradient-to-r from-transparent via-maxfit-neon-green to-transparent transform -translate-y-1/2"></div>

          <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-8">
            {steps.map((step, index) => (
              <div key={index} className="relative text-center group">
                {/* Step Number */}
                <div className="relative z-10 mb-6">
                  <div className="w-20 h-20 bg-maxfit-neon-green/10 border-2 border-maxfit-neon-green rounded-full flex items-center justify-center mx-auto mb-4 group-hover:bg-maxfit-neon-green/20 transition-all duration-300">
                    <step.icon className="w-8 h-8 text-maxfit-neon-green" />
                  </div>
                  <div className="absolute -top-3 -right-3 w-8 h-8 bg-maxfit-neon-green rounded-full flex items-center justify-center">
                    <span className="text-maxfit-black font-bold text-sm">{step.step}</span>
                  </div>
                </div>

                <h3 className="text-xl font-bold text-white mb-3 group-hover:text-maxfit-neon-green transition-colors duration-300">
                  {step.title}
                </h3>
                <p className="text-gray-300 leading-relaxed">{step.description}</p>

                {/* Mobile Connection Arrow */}
                {index < steps.length - 1 && (
                  <div className="lg:hidden flex justify-center mt-8 mb-4">
                    <div className="w-0.5 h-8 bg-maxfit-neon-green/50"></div>
                  </div>
                )}
              </div>
            ))}
          </div>
        </div>

        {/* CTA Section */}
        <div className="text-center mt-16">
          <div className="glass-card p-8 rounded-2xl max-w-2xl mx-auto">
            <h3 className="text-2xl font-bold text-white mb-4">Ready to Transform Your Fitness?</h3>
            <p className="text-gray-300 mb-6">
              Join thousands of users who have already started their AI-powered fitness journey
            </p>
            <Link href="/signup">
              <button className="btn-neon px-8 py-3 rounded-lg font-semibold transition-all duration-300">
                Get Started Now
              </button>
            </Link>
          </div>
        </div>
      </div>
    </section>
  )
}

export default HowItWorks
